import {
  User,
  Tender,
  Bidder,
  Document,
  ComplianceResult,
  RiskScore,
  AIRecommendation,
  GovernmentVerification,
  AuditLog,
  DashboardStats,
} from '../types';

export const MOCK_USER: User = {
  id: 'usr_officer_01',
  email: 'officer@bidsure.gov.in',
  full_name: 'Rajesh Kumar, GeM Procurement Scrutiny Officer',
  role: 'PROCUREMENT_OFFICER',
  is_active: true,
  created_at: '2026-01-15T09:00:00Z',
};

export const MOCK_TENDERS: Tender[] = [
  {
    id: 'tnd_demo_001',
    tender_number: 'GEM/2026/B/DEMO001',
    title: 'Industrial Heavy-Duty Centrifugal Pump Procurement',
    description: 'Supply, installation, and commissioning of high-discharge industrial centrifugal pumps for state irrigation projects.',
    category: 'Machinery & Capital Equipment',
    estimated_value: 450000000.0,
    closing_date: '2026-10-15T18:00:00Z',
    status: 'ACTIVE',
    bidders_count: 3,
    average_score: 74.5,
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-09-10T14:30:00Z',
    requirements: [
      {
        id: 'req_01',
        tender_id: 'tnd_demo_001',
        rule_type: 'TURNOVER',
        description: 'Minimum average annual turnover for past 3 years >= ₹10.0 Crore',
        min_value: 100000000.0,
        currency: 'INR',
        weight: 20.0,
        mandatory: true,
        is_critical: true,
        expected_text: '>= ₹10.0 Crore',
        created_at: '2026-08-01T10:00:00Z',
      },
      {
        id: 'req_02',
        tender_id: 'tnd_demo_001',
        rule_type: 'GST',
        description: 'Valid Goods and Services Tax (GSTIN) registration with active status',
        weight: 15.0,
        currency: 'INR',
        mandatory: true,
        is_critical: false,
        expected_text: 'Active GSTIN',
        created_at: '2026-08-01T10:00:00Z',
      },
      {
        id: 'req_03',
        tender_id: 'tnd_demo_001',
        rule_type: 'PAN',
        description: 'Valid Permanent Account Number (PAN) issued by Income Tax Department',
        weight: 10.0,
        currency: 'INR',
        mandatory: true,
        is_critical: false,
        expected_text: 'Valid PAN Card',
        created_at: '2026-08-01T10:00:00Z',
      },
      {
        id: 'req_04',
        tender_id: 'tnd_demo_001',
        rule_type: 'LOCAL_CONTENT',
        description: 'Minimum local value addition percentage (Make in India Policy) >= 50%',
        min_value: 50.0,
        weight: 20.0,
        currency: 'INR',
        mandatory: true,
        is_critical: true,
        expected_text: '>= 50% Local Content',
        created_at: '2026-08-01T10:00:00Z',
      },
      {
        id: 'req_05',
        tender_id: 'tnd_demo_001',
        rule_type: 'BLACKLISTING',
        description: 'Non-debarment / non-blacklisting affidavit on non-judicial stamp paper',
        weight: 15.0,
        currency: 'INR',
        mandatory: true,
        is_critical: true,
        expected_text: 'Clean Affidavit',
        created_at: '2026-08-01T10:00:00Z',
      },
      {
        id: 'req_06',
        tender_id: 'tnd_demo_001',
        rule_type: 'OEM_AUTHORIZATION',
        description: 'OEM Authorization Certificate for centrifugal pumps',
        weight: 20.0,
        currency: 'INR',
        mandatory: true,
        is_critical: true,
        expected_text: 'Valid OEM Authorization',
        created_at: '2026-08-01T10:00:00Z',
      },
    ],
  },
  {
    id: 'tnd_demo_002',
    tender_number: 'GEM/2026/B/DEMO002',
    title: 'Hospital ICU Invasive Ventilator & Patient Monitor System',
    description: 'Turnkey procurement of CE/FDA certified ICU ventilators with telemetry for district hospitals.',
    category: 'Medical & Healthcare Devices',
    estimated_value: 120000000.0,
    closing_date: '2026-11-05T17:00:00Z',
    status: 'ACTIVE',
    bidders_count: 2,
    average_score: 91.0,
    created_at: '2026-08-10T11:00:00Z',
    updated_at: '2026-09-08T16:00:00Z',
  },
  {
    id: 'tnd_demo_003',
    tender_number: 'GEM/2026/B/DEMO003',
    title: 'Secure Cloud Infrastructure & Sovereign Compute Facility',
    description: 'MeitY empaneled sovereign cloud services for ministry core databases.',
    category: 'Information Technology & Cloud',
    estimated_value: 850000000.0,
    closing_date: '2026-09-30T15:00:00Z',
    status: 'EVALUATION',
    bidders_count: 4,
    average_score: 82.3,
    created_at: '2026-07-20T08:30:00Z',
    updated_at: '2026-09-09T18:00:00Z',
  },
];

export const MOCK_BIDDERS: Bidder[] = [
  {
    id: 'bid_abc001',
    tender_id: 'tnd_demo_001',
    company_name: 'ABC Engineering Pvt Ltd',
    cin: 'U29100DL2012PTC234567',
    pan: 'AABCA1234F',
    gstin: '07AABCA1234F1Z5',
    udyam_number: 'UDYAM-DL-01-0012345',
    contact_email: 'compliance@abcengineering.co.in',
    contact_phone: '+91 98112 34567',
    submitted_at: '2026-08-25T14:32:00Z',
    compliance_score: 52,
    risk_level: 'HIGH',
    verification_status: 'VERIFIED',
    officer_decision_status: 'UNDER_REVIEW',
    documents_count: 7,
    passed_requirements: 3,
    failed_requirements: 2,
    warning_requirements: 1,
    missing_requirements: 0,
  },
  {
    id: 'bid_nbm002',
    tender_id: 'tnd_demo_001',
    company_name: 'National Bharat Motors Ltd',
    cin: 'L34100MH1998PLC012987',
    pan: 'AABCN9876K',
    gstin: '27AABCN9876K1Z9',
    udyam_number: 'UDYAM-MH-02-0098765',
    contact_email: 'tenders@bharatmotors.in',
    contact_phone: '+91 98220 12345',
    submitted_at: '2026-08-26T10:15:00Z',
    compliance_score: 95,
    risk_level: 'LOW',
    verification_status: 'VERIFIED',
    officer_decision_status: 'APPROVED',
    documents_count: 8,
    passed_requirements: 6,
    failed_requirements: 0,
    warning_requirements: 0,
    missing_requirements: 0,
  },
  {
    id: 'bid_shi003',
    tender_id: 'tnd_demo_001',
    company_name: 'Sunrise Heavy Infotech',
    cin: 'U72200KA2015PTC081234',
    pan: 'AABCS5432M',
    gstin: '29AABCS5432M1Z2',
    udyam_number: 'UDYAM-KR-03-0054321',
    contact_email: 'bids@sunriseinfotech.com',
    contact_phone: '+91 98450 67890',
    submitted_at: '2026-08-27T16:45:00Z',
    compliance_score: 41,
    risk_level: 'HIGH',
    verification_status: 'FAILED',
    officer_decision_status: 'REJECTED',
    documents_count: 5,
    passed_requirements: 2,
    failed_requirements: 3,
    warning_requirements: 1,
    missing_requirements: 1,
  },
];

export const MOCK_COMPLIANCE_RESULTS: ComplianceResult[] = [
  {
    id: 'comp_01',
    bidder_id: 'bid_abc001',
    requirement_id: 'req_01',
    rule_name: 'Annual Turnover Requirement (>= ₹10 Cr)',
    status: 'FAIL',
    score: 0,
    confidence: 0.98,
    reason: 'Reported audited turnover of ₹8.4 Crore in Balance Sheet fails the mandatory minimum threshold of ₹10.0 Crore. Cross-check with ITR AY 2025-26 confirmed ₹8.38 Crore gross receipts.',
    expected_value: '>= ₹10,00,00,000.00',
    actual_value: '₹8,40,00,000.00 (ITR: ₹8,38,12,000.00)',
    difference: '-₹1.60 Crore (-16.0% deficit)',
    evidence_document_id: 'doc_bs_01',
    evidence_document_name: 'ABC_Eng_BalanceSheet.pdf',
    evidence_page_number: '3',
    evidence_snippet: 'Statement of Profit and Loss: Revenue from Operations for FY 2024-25 stands at INR 8,40,24,000 (Eight Crore Forty Lakhs Twenty-Four Thousand).',
    created_at: '2026-08-25T15:00:00Z',
  },
  {
    id: 'comp_02',
    bidder_id: 'bid_abc001',
    requirement_id: 'req_04',
    rule_name: 'Make in India Local Content (>= 50%)',
    status: 'WARNING',
    score: 60,
    confidence: 0.92,
    reason: 'Self-certification claims 58% local content, but imported bill of entry attached under Annexure III lists critical pump impeller assemblies sourced from Germany amounting to 49% of value.',
    expected_value: '>= 50.0% verified domestic value add',
    actual_value: '58.0% declared (calculated net: ~51.2%)',
    difference: 'Marginal compliance; requires auditor spot-check',
    evidence_document_id: 'doc_mii_01',
    evidence_document_name: 'ABC_Eng_MakeInIndia.pdf',
    evidence_page_number: '1',
    evidence_snippet: 'We hereby declare that domestic value addition in the manufacturing of centrifugal pump sets equals 58.0% as certified by our cost accountant.',
    created_at: '2026-08-25T15:00:00Z',
  },
  {
    id: 'comp_03',
    bidder_id: 'bid_abc001',
    requirement_id: 'req_02',
    rule_name: 'GSTIN Registration Verification',
    status: 'PASS',
    score: 100,
    confidence: 1.0,
    reason: 'GSTIN 07AABCA1234F1Z5 is ACTIVE and verified in real-time against GSTN Gateway. Returns GSTR-3B filed up to July 2026.',
    expected_value: 'Active GSTIN',
    actual_value: 'Active - Filing status up to date',
    evidence_document_id: 'doc_gst_01',
    evidence_document_name: 'ABC_Eng_GST.pdf',
    evidence_page_number: '1',
    evidence_snippet: 'Government of India - GST Registration Certificate. Legal Name: ABC Engineering Private Limited. Status: Active Regular Taxpayer.',
    created_at: '2026-08-25T15:00:00Z',
  },
  {
    id: 'comp_04',
    bidder_id: 'bid_abc001',
    requirement_id: 'req_03',
    rule_name: 'PAN Identity & CBDT Verification',
    status: 'PASS',
    score: 100,
    confidence: 0.99,
    reason: 'PAN AABCA1234F is active and matched against CBDT database with 100% name correlation.',
    expected_value: 'Valid PAN Card',
    actual_value: 'AABCA1234F (Valid & Seeded)',
    evidence_document_id: 'doc_pan_01',
    evidence_document_name: 'ABC_Eng_PAN.pdf',
    evidence_page_number: '1',
    evidence_snippet: 'Income Tax Department, Govt. of India. Permanent Account Number: AABCA1234F. Name: ABC ENGINEERING PRIVATE LIMITED.',
    created_at: '2026-08-25T15:00:00Z',
  },
  {
    id: 'comp_05',
    bidder_id: 'bid_abc001',
    requirement_id: 'req_05',
    rule_name: 'Debarment & Non-Blacklisting Affidavit',
    status: 'PASS',
    score: 100,
    confidence: 0.95,
    reason: 'Affidavit notarized on ₹100 stamp paper dated 20-Aug-2026 verified. CPPP debarment database returned no match.',
    expected_value: 'Clean Non-Debarment Affidavit',
    actual_value: 'Affidavit Verified (No Debarment Record)',
    evidence_document_id: 'doc_aff_01',
    evidence_document_name: 'ABC_Eng_Blacklisting_Affidavit.pdf',
    evidence_page_number: '1',
    evidence_snippet: 'I, Director of ABC Engineering Pvt Ltd, affirm that the firm has never been debarred or blacklisted by GeM, CPPP, or any PSU.',
    created_at: '2026-08-25T15:00:00Z',
  },
  {
    id: 'comp_06',
    bidder_id: 'bid_abc001',
    requirement_id: 'req_06',
    rule_name: 'OEM Manufacturer Authorization',
    status: 'FAIL',
    score: 0,
    confidence: 0.97,
    reason: 'Bidder submitted an expired dealer authorization certificate dated 2024 with validity ending 31-Dec-2025. Does not cover 2026 tender lifecycle.',
    expected_value: 'Valid OEM Authorization through 2027',
    actual_value: 'Authorization expired on 31-Dec-2025',
    difference: 'Expired certificate invalid for mandatory technical qualification',
    evidence_document_id: 'doc_oem_01',
    evidence_document_name: 'ABC_Eng_MakeInIndia.pdf',
    evidence_page_number: '2',
    evidence_snippet: 'Validity: This authorization is effective from 01-Jan-2024 and expires unconditionally on 31-Dec-2025.',
    created_at: '2026-08-25T15:00:00Z',
  },
];

export const MOCK_RISK_SCORE: RiskScore = {
  id: 'rsk_abc001',
  bidder_id: 'bid_abc001',
  numerical_score: 78.0,
  risk_level: 'HIGH',
  critical_override_applied: true,
  override_reason: 'Automatic High-Risk Flag triggered due to failure of mandatory critical criteria: Annual Turnover deficit (-16.0%) and Expired OEM Authorization.',
  breakdown: {
    financial_risk: 85,
    technical_compliance_risk: 72,
    statutory_registry_risk: 15,
    legal_debarment_risk: 5,
  },
  calculated_at: '2026-08-25T15:05:00Z',
};

export const MOCK_AI_RECOMMENDATION: AIRecommendation = {
  id: 'rec_abc001',
  bidder_id: 'bid_abc001',
  overall_assessment: 'Disqualification Recommended on Technical & Financial Grounds',
  key_issues: [
    'Annual Turnover ₹8.4 Cr falls short of mandatory ₹10.0 Cr tender requirement (rule 161 of GFR 2017 non-compliant).',
    'OEM Manufacturer Authorization is expired (validity lapsed 31-Dec-2025).',
    'Make-in-India declaration contains conflicting assembly import bills from Germany requiring physical verification.',
  ],
  positive_checks: [
    'GSTIN is active with verified GSTR-3B filings.',
    'PAN matched with 100% confidence against CBDT records.',
    'No active blacklisting/debarment found across CPPP/GeM watchlists.',
  ],
  recommendation_text: 'Issue formal Technical Disqualification notice or request clarification under GeM Clause 4.12 regarding valid OEM authorization within 48 hours.',
  advisory_disclaimer: 'AI-generated assessment is advisory in nature pursuant to CVC Circular 03/05/23. The final procurement decision rests exclusively with the designated GeM Competent Authority.',
  generated_at: '2026-08-25T15:05:00Z',
};

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: 'doc_bs_01',
    bidder_id: 'bid_abc001',
    document_type: 'BALANCE_SHEET',
    original_filename: 'ABC_Eng_BalanceSheet.pdf',
    file_size: 1998,
    mime_type: 'application/pdf',
    total_pages: 3,
    ocr_status: 'COMPLETED',
    created_at: '2026-08-25T14:32:00Z',
  },
  {
    id: 'doc_itr_01',
    bidder_id: 'bid_abc001',
    document_type: 'ITR_RETURN',
    original_filename: 'ABC_Eng_ITR_AY2025.pdf',
    file_size: 11993,
    mime_type: 'application/pdf',
    total_pages: 4,
    ocr_status: 'COMPLETED',
    created_at: '2026-08-25T14:32:00Z',
  },
  {
    id: 'doc_gst_01',
    bidder_id: 'bid_abc001',
    document_type: 'GST_CERTIFICATE',
    original_filename: 'ABC_Eng_GST.pdf',
    file_size: 3133,
    mime_type: 'application/pdf',
    total_pages: 1,
    ocr_status: 'COMPLETED',
    created_at: '2026-08-25T14:32:00Z',
  },
  {
    id: 'doc_pan_01',
    bidder_id: 'bid_abc001',
    document_type: 'PAN_CARD',
    original_filename: 'ABC_Eng_PAN.pdf',
    file_size: 1734,
    mime_type: 'application/pdf',
    total_pages: 1,
    ocr_status: 'COMPLETED',
    created_at: '2026-08-25T14:32:00Z',
  },
  {
    id: 'doc_mii_01',
    bidder_id: 'bid_abc001',
    document_type: 'MAKE_IN_INDIA_CERTIFICATE',
    original_filename: 'ABC_Eng_MakeInIndia.pdf',
    file_size: 4206,
    mime_type: 'application/pdf',
    total_pages: 2,
    ocr_status: 'COMPLETED',
    created_at: '2026-08-25T14:32:00Z',
  },
  {
    id: 'doc_aff_01',
    bidder_id: 'bid_abc001',
    document_type: 'BLACKLISTING_AFFIDAVIT',
    original_filename: 'ABC_Eng_Blacklisting_Affidavit.pdf',
    file_size: 2233,
    mime_type: 'application/pdf',
    total_pages: 1,
    ocr_status: 'COMPLETED',
    created_at: '2026-08-25T14:32:00Z',
  },
  {
    id: 'doc_udyam_01',
    bidder_id: 'bid_abc001',
    document_type: 'UDYAM_CERTIFICATE',
    original_filename: 'ABC_Eng_Udyam.pdf',
    file_size: 1886,
    mime_type: 'application/pdf',
    total_pages: 1,
    ocr_status: 'COMPLETED',
    created_at: '2026-08-25T14:32:00Z',
  },
];

export const MOCK_VERIFICATIONS: GovernmentVerification[] = [
  {
    id: 'ver_01',
    bidder_id: 'bid_abc001',
    source: 'MCA_21',
    query_param: 'U29100DL2012PTC234567',
    status: 'VERIFIED',
    raw_response: {
      company_name: 'ABC ENGINEERING PRIVATE LIMITED',
      roc_code: 'RoC-Delhi',
      class_of_company: 'Private',
      company_status: 'Active',
      paid_up_capital: '₹2,50,00,000',
      directors: ['Sunil Verma (DIN: 01234567)', 'Anjali Sharma (DIN: 07654321)'],
    },
    is_simulated: true,
    verified_at: '2026-08-25T14:35:00Z',
  },
  {
    id: 'ver_02',
    bidder_id: 'bid_abc001',
    source: 'GSTN_GATEWAY',
    query_param: '07AABCA1234F1Z5',
    status: 'VERIFIED',
    raw_response: {
      trade_name: 'ABC ENGINEERING',
      constitution: 'Private Limited Company',
      taxpayer_type: 'Regular',
      active_status: true,
      last_return_filed: 'July 2026 (GSTR-3B)',
    },
    is_simulated: true,
    verified_at: '2026-08-25T14:35:02Z',
  },
  {
    id: 'ver_03',
    bidder_id: 'bid_abc001',
    source: 'CPPP_DEBARMENT',
    query_param: 'AABCA1234F',
    status: 'VERIFIED',
    raw_response: {
      match_found: false,
      debarment_status: 'CLEAN',
      watchlists_checked: ['GeM Incident Management', 'CPPP Blacklist', 'MoF Vigilance Portal'],
    },
    is_simulated: true,
    verified_at: '2026-08-25T14:35:05Z',
  },
  {
    id: 'ver_04',
    bidder_id: 'bid_abc001',
    source: 'EPFO_SHRAM_SUVIDHA',
    query_param: 'DLCPM0012345000',
    status: 'VERIFIED',
    raw_response: {
      establishment_status: 'Active Exempted',
      contributing_members: 142,
      last_ecr_month: 'July 2026',
    },
    is_simulated: true,
    verified_at: '2026-08-25T14:35:08Z',
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud_01',
    user_email: 'officer@bidsure.gov.in',
    action: 'TENDER_OPENED',
    entity_type: 'TENDER',
    entity_id: 'tnd_demo_001',
    new_value: { status: 'ACTIVE', opening_date: '2026-08-01' },
    ip_address: '10.14.82.11 (NIC VPN Gateway)',
    timestamp: '2026-08-01T10:00:00Z',
  },
  {
    id: 'aud_02',
    user_email: 'bidder@abcengineering.co.in',
    action: 'BID_SUBMITTED',
    entity_type: 'BIDDER',
    entity_id: 'bid_abc001',
    new_value: { document_count: 7, quoted_price: '₹42.50 Cr' },
    ip_address: '103.21.124.9',
    timestamp: '2026-08-25T14:32:00Z',
  },
  {
    id: 'aud_03',
    user_email: 'system@bidsure.gov.in',
    action: 'OCR_PIPELINE_EXECUTED',
    entity_type: 'DOCUMENT',
    entity_id: 'doc_bs_01',
    new_value: { ocr_pages: 3, entities_extracted: 14 },
    ip_address: '127.0.0.1',
    timestamp: '2026-08-25T14:33:00Z',
  },
  {
    id: 'aud_04',
    user_email: 'system@bidsure.gov.in',
    action: 'COMPLIANCE_EVALUATION_COMPLETED',
    entity_type: 'COMPLIANCE',
    entity_id: 'bid_abc001',
    new_value: { score: 52, risk_level: 'HIGH', critical_override: true },
    ip_address: '127.0.0.1',
    timestamp: '2026-08-25T15:05:00Z',
  },
  {
    id: 'aud_05',
    user_email: 'officer@bidsure.gov.in',
    action: 'SCRUTINY_REVIEW_INITIATED',
    entity_type: 'OFFICER_DECISION',
    entity_id: 'bid_abc001',
    new_value: { status: 'UNDER_REVIEW' },
    ip_address: '10.14.82.11 (NIC VPN Gateway)',
    timestamp: '2026-08-26T09:15:00Z',
  },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  total_tenders: 18,
  active_tenders: 7,
  total_bidders: 42,
  bidders_under_review: 6,
  average_compliance_score: 76.4,
  high_risk_bidders: 4,
  compliance_distribution: {
    low: 26,
    medium: 12,
    high: 4,
  },
  status_distribution: {
    PASS: 184,
    WARNING: 28,
    FAIL: 14,
    MISSING: 6,
  },
  recent_tenders: MOCK_TENDERS,
  high_risk_bidder_list: MOCK_BIDDERS.filter((b) => b.risk_level === 'HIGH'),
};
